import type { Metadata } from "next";
import { Playfair_Display, Merriweather } from 'next/font/google'
import "./globals.css";
import { Suspense } from "react";
import Preloader from "@/components/PreLoader/PreLoader";
import PreloaderManager from "@/components/PreLoader/PreloaderManager";
import AnimatedFooter from "@/components/Footer";

const playfair = Playfair_Display({ 
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-playfair',
})

const merriweather = Merriweather({ 
  weight: ['300', '400', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-merriweather',
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${playfair.variable} ${merriweather.variable}`}>
        <PreloaderManager>{children}</PreloaderManager>
        <AnimatedFooter/>
      </body>
    </html>
  );
}
